ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_raw_daily`
ADD COLUMN IF NOT EXISTS valid_lead BOOL;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_raw_daily`
ADD COLUMN IF NOT EXISTS valid_lead_raw STRING;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_raw_daily`
ADD COLUMN IF NOT EXISTS lead_summary STRING;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_raw_daily`
ADD COLUMN IF NOT EXISTS is_spam BOOL;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_raw_daily`
ADD COLUMN IF NOT EXISTS is_spam_raw STRING;

ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_data`
ADD COLUMN IF NOT EXISTS valid_lead BOOL;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_data`
ADD COLUMN IF NOT EXISTS valid_lead_raw STRING;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_data`
ADD COLUMN IF NOT EXISTS lead_summary STRING;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_data`
ADD COLUMN IF NOT EXISTS is_spam BOOL;
ALTER TABLE `data-etl-to-bigquery.ctm_data.activities_data`
ADD COLUMN IF NOT EXISTS is_spam_raw STRING;

CREATE OR REPLACE VIEW `data-etl-to-bigquery.ctm_data.activities_combined` AS
SELECT
  batch.*,
  CAST(NULL AS BOOL) AS valid_lead,
  CAST(NULL AS STRING) AS valid_lead_raw,
  CAST(NULL AS STRING) AS lead_summary,
  CAST(NULL AS BOOL) AS is_spam,
  CAST(NULL AS STRING) AS is_spam_raw
FROM `data-etl-to-bigquery.ctm_data.activities_raw_final_batch` AS batch

UNION DISTINCT

SELECT
  id,
  sid,
  account_id,
  account_name,
  CAST(NULL AS INT64) AS batch_number,
  CAST(NULL AS STRING) AS processed_at,
  name,
  cnam,
  search,
  referrer,
  location,
  source,
  source_id,
  source_sid,
  tgid,
  likelihood,
  CAST(duration AS FLOAT64) AS duration,
  direction,
  talk_time,
  ring_time,
  hold_time,
  wait_time,
  parent_id,
  email,
  street,
  city,
  state,
  country,
  postal_code,
  called_at,
  unix_time,
  tracking_number_id,
  tracking_number_sid,
  tracking_number,
  tracking_label,
  dial_status,
  is_new_caller,
  indexed_at,
  inbound_rate_center,
  business_number,
  business_label,
  receiving_number_id,
  receiving_number_sid,
  billed_amount,
  CAST(billed_at AS TIMESTAMP) AS billed_at,
  caller_number_split,
  contact_number,
  excluded,
  redacted,
  tracking_number_format,
  business_number_format,
  caller_number_format,
  caller_number_complete,
  caller_number_bare,
  tracking_number_bare,
  caller_number,
  CAST(visitor AS STRING) AS visitor,
  call_path,
  left_talk_time,
  right_talk_time,
  transfers,
  call_status,
  status,
  spotted,
  salesforce,
  callbacks,
  emails,
  day,
  month,
  hour,
  ga,
  tag_list,
  CAST(NULL AS STRING) AS notes,
  latitude,
  longitude,
  extended_lookup_on,
  legs,
  _timestamp,
  visitor_sid,
  agent_insights,
  duration_period,
  alternative_number,
  paid,
  inputs,
  geo,
  last_location,
  audio,
  is_s3_link,
  webvisit,
  web_source,
  medium,
  visitor_ip,
  campaign,
  keyword,
  ad_match_type,
  ad_content,
  ad_slot,
  ad_slot_position,
  ad_network,
  creative_id,
  ad_group_id,
  adgroup_id,
  campaign_id,
  ad_format,
  CAST(ad_targeting_type AS STRING) AS ad_targeting_type,
  keyword_id,
  CAST(NULL AS STRING) AS ms,
  CAST(NULL AS FLOAT64) AS caller_number_blocked,
  CAST(NULL AS STRING) AS message_id,
  CAST(NULL AS STRING) AS message_body,
  CAST(NULL AS STRING) AS message_media,
  CAST(NULL AS STRING) AS sms_error_code,
  CAST(NULL AS STRING) AS sale,
  CAST(NULL AS STRING) AS agent_id,
  CAST(NULL AS STRING) AS agent,
  CAST(NULL AS STRING) AS carrier,
  CAST(NULL AS STRING) AS spam,
  CAST(NULL AS STRING) AS extended_lookup,
  CAST(NULL AS STRING) AS form,
  CAST(NULL AS STRING) AS chat_messages,
  CAST(NULL AS STRING) AS chat_status,
  CAST(NULL AS STRING) AS chat_type,
  99 AS source_batch,
  CAST(NULL AS STRING) AS transcription,
  CAST(NULL AS STRING) AS transcription_text,
  CAST(NULL AS STRING) AS summary,
  valid_lead,
  valid_lead_raw,
  lead_summary,
  is_spam,
  is_spam_raw
FROM `data-etl-to-bigquery.ctm_data.activities_raw_daily`;
